### ISSUE TITLE
504 Gateway Time-out in layer details page

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#108]
This happens frequently. We need to investigate and figure out where the timeout is raised.

**Comment by capooti** [comment]
I am pretty sure this is because of slow GeoNetwork response time.

The view makes a call to the metadata_csw model method, that send a getrecordbyid request to GeoNetwork.
@ingenieroariel I think we should increase time out here, what do you think?

In any case, a part from timeout issues, @mbertrand not sure why do we need to query the catalog at all, shouldn't be the needed information already in the GeoNode catalogue, and thus in the model attributes?
And checking well, this line [1] seems stale to me, as the metadata variable does not seem to be used in the template [2], so the call to GeoNetwork seems totally unneeded to me.
If you can confirm me I will remove it and we should be fine it with this problem.

[1] https://github.com/cga-harvard/cga-worldmap/blob/legacy/geonode/maps/views.py#L1166
[2] https://github.com/cga-harvard/cga-worldmap/blob/legacy/geonode/templates/maps/layer.html

**Comment by ingenieroariel** [comment]
The call to geonetwork was removed in 1.2 for precisely those reasons.
Better to take it out if we can.
