### ISSUE TITLE
Add terms of use for map creation

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#128]
Add terms of use for account creation and map creation as we have currently for layer creation and layer upload.  Here is link to TOS http://about.worldmap.harvard.edu/terms-and-conditions

**Comment by capooti** [comment]
So, should I add a link to TOS in the user registration page (https://worldmap.harvard.edu/accounts/register/), and maybe in the Save form (where you can also put the title and the abstract) on this page? https://worldmap.harvard.edu/maps/new

**Comment by blewis** [comment]
yes, and user must check box saying agree as now with layers 
![image](https://cloud.githubusercontent.com/assets/812849/18730386/1644f212-8024-11e6-9f7c-e485441a4b09.png)

**Comment by capooti** [comment]
oh I see

**Comment by capooti** [comment]
For now we implement it only in account creation.

**Comment by capooti** [comment]
Done it. @bglewis check it and close it, thanks.
