### ISSUE TITLE
Fix Solr grid request:  Type should not be geohash grid, but use quad tree request

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#132]
Fix Solr grid request:  Type should not be geohash grid, but use quad tree request to get 1/4 instead of 1/32 heatmap resolution control.

**Comment by dsmiley** [comment]
This is my config in the BOP.

```
  <!-- BOP: Optimized for heatmaps, and we use it for filtering too (although we'd like to use new
  Lucene stuff instead for filtering once there are Solr adapters).
  For more heatmap resolution choices we use a quad tree.  To make the cells square, we use a
  square worldBounds (although now we can't span the dateline since this necessitates geo=false).
  Once FlexPrefixTree is available, we needn't set geo=false, and we can have fewer levels at the
  top especially to save space.  5 meter precision (specified in units of degrees).
   TODO want FlexPrefixTree when it's ready -->
  <fieldType name="geo_rpt_5m" class="solr.SpatialRecursivePrefixTreeFieldType"
             geo="false" worldBounds="ENVELOPE(-180, 180, 180, -180)" prefixTree="packedQuad"
             distErrPct="0.025" maxDistErr="0.000045" distanceUnits="degrees" />
```

**Comment by capooti** [comment]
thanks @dsmiley will look into this

**Comment by blewis** [comment]
After switching to quad tree from geohash heatmap view is now very coarse.  I assume that with a combination of tweaking on the query side and on the client rendering side we can tighten up the rendering so that it is meaningful.
https://github.com/cga-harvard/cga-worldmap/issues/132

**Comment by dsmiley** [comment]
It should simply be a matter of tweaking the `facet.heatmap.distErrPct` figure.  It defaults to 0.15... make it smaller for more detailed heatmap.  The fact that it's consistent across scales is a good thing :-)

**Comment by blewis** [comment]
Thanks @dsmiley!

**Comment by capooti** [comment]
@dsmiley I am not sure where facet.heatmap.distErrPct should be set

**Comment by capooti** [comment]
figured out, thanks

**Comment by capooti** [comment]
I think this can be closed?
