### ISSUE TITLE
Fix double scroll bars on search window for Chrome on Windows

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#134]
Fix double scroll bars on search window.  These appear regardless of screen resolution.  Chrome V 53 also latest firefox, windows.

![image](https://cloud.githubusercontent.com/assets/812849/18728965/b7a93e76-801d-11e6-9390-91332ee5c27f.png)

**Comment by capooti** [comment]
@ingenieroariel I need your help here, as I think Guillermo worked on it.

**Comment by blewis** [comment]
this seems to be done.  thanks Guillermo

**Comment by blewis** [comment]
This seems to be fixed on windows machines in Firefox but not in Chrome

**Comment by ingenieroariel** [comment]
@gsolat can you try in Windows + Chrome and replicate?

**Comment by gsolat** [comment]
@ingenieroariel Could not replicate the issue. Windows + Chrome: 

![hypermap-chrome](https://cloud.githubusercontent.com/assets/5114135/19132868/2855957c-8b1b-11e6-985e-b0f9c48f9c5e.png)
