### ISSUE TITLE
Text changes in gazetteer UI

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#142]
"Custom Gazetteer Name" instead of "Project"
Indicate that using fields for dates will override any dates in metadata

**Comment by capooti** [comment]
done it. You will see it on the next deployment @bglewis

**Comment by capooti** [comment]
this is in production now @bglewis so you can close it

**Comment by blewis** [comment]
i added a layer to the gazetteer http://worldmap.harvard.edu/data/geonode:ports_sale_confident_ggx and when I go back to the metadata page it appears ready to submit the same data again.
![image](https://cloud.githubusercontent.com/assets/812849/19289935/14ec55c4-8fdb-11e6-9fa2-d7f19d580f4b.png)

If I submit again, it appears there is not two copies of each feature in the gazetteer (which is as it should be).  Once a layer has been added to the gazetteer it should not be possible to try to re-add however.  It should be possible to remove the data from whatever gazetteer(s) it was added to however.  Once a layer has been added the metadata page should be returned and it should say in the Attribute Section at the bottom: "Included in Gazetteer <name of gazetteer>".  Remove from <name of gazetteer>"

**Comment by capooti** [comment]
You mean if you submit the form using two different custom gazetteer names?

**Comment by capooti** [comment]
This is done. @bglewis please check if it is as expected and then close it.
