### ISSUE TITLE
Zoom to map extent doesn't work for remote service layers

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#147]
In GPX client in http://hypersearch.cga.terranodo.io/maps/new
remote layers do not support "zoom-to-extent" from right click on layer

![image](https://cloud.githubusercontent.com/assets/812849/19041560/88a02bfc-8956-11e6-926d-b1f6cf456529.png)

**Comment by ingenieroariel** [comment]
@simod this was the issue I told you about
