### ISSUE TITLE
Remove "External Data" tab from Add Layers window, remove "More..." pulldown from map.

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#148]
Remove "External Data" tab from Add Layers window, remove "More..." pulldown from map.

**Comment by capooti** [comment]
You mean those ones, correct?

<img width="841" alt="screenshot 2016-10-04 14 38 20" src="https://cloud.githubusercontent.com/assets/148380/19087529/51e741be-8a40-11e6-9932-1ed930391136.png">

<img width="289" alt="screenshot 2016-10-04 14 38 54" src="https://cloud.githubusercontent.com/assets/148380/19087534/560e51ce-8a40-11e6-84fc-ca05b1740527.png">

**Comment by blewis** [comment]
Yes

Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
I am doing this on the hypersearch branch, correct?
as it does not make sense them to remove from master until we do not have a replacement

**Comment by blewis** [comment]
Yes

Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>
