### ISSUE TITLE
Save map bug

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#153]
After adding several layers to the map, once map is saved all layers become changed to the same layer content.  Layer name does not change. Example http://hypersearch.cga.terranodo.io/maps/Cambridge-dev

**Comment by capooti** [comment]
Seems working properly using WM layers (see here: http://hypersearch.cga.terranodo.io/maps/11162)
will make some more tests

**Comment by blewis** [comment]
This was just made in Chrome http://hypersearch.cga.terranodo.io/maps/bentest51

**Comment by blewis** [comment]
There does not seem to be a problem when all layers are worldmap layers, but when all are remote it happens.

**Comment by capooti** [comment]
This is most likely caused by MapProxy not caching layers. I am checking this with @ingenieroariel in the slack channel right now
