### ISSUE TITLE
Add form for public to submit map service endpoints for harvesting

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#154]
One endpoint at a time rather than batch.  Available to users who are not logged in.  The form should capture the service endpoint URL, service type (if known), and optional name of organization field and description field and depict date estimate.  User will be told the information will be checked and user will be notified when the service has been added.  Information will be logged to a google sheet for human review and implementation.

**Comment by capooti** [comment]
A form in Django with following fields:
* description
* url

Add a link in the "Add layers" dialog opening a new page with the form.

**Comment by capooti** [comment]
@bglewis I am working on this. What would be a way to get notified when a new endpoint is added?

**Comment by capooti** [comment]
Implemented. I need to add the link in the GXP interface now.

**Comment by capooti** [comment]
@bglewis I have added the link in the GeoExplorer interface. You can see how it looks in hypersearch. Let me know if you have any integrations/modifications before I deploy this to production.

**Comment by capooti** [comment]
This is in production now.
