### ISSUE TITLE
"Trouble saving features" message (Firefox and Chrome, Windows 8)

### ISSUE THREAD

**Issue by atomrab** [cga-harvard/cga-worldmap#155]
When I am signed in and attempt to save a feature I have added (using the "Create Feature" menu item) to a layer in an existing map, I see the following message:

![worldmaperror](https://cloud.githubusercontent.com/assets/4740995/19607597/84e4bf62-9790-11e6-8796-d0d290c63a7c.JPG)

This happens in both Firefox and Chrome (both up-to-date). Furthermore, if I select "Edit Feature" and attempt to edit one of the existing features, the data table opens only for a split second, but will not stay open so that I can edit fields (it will stay open occasionally, but only in response to a very specific click pattern -- and if I make an edit, the same "Trouble saving features" message appears).

**Comment by capooti** [comment]
Thanks @atomrab for reporting this. We are aware of it and working to fix it.

**Comment by blewis** [comment]
Hi Adam,
Yes I thought we had killed this bug but it has come back.  We are working on it now.  Sorry about that!
Cheers,
Ben

Ben Lewis
Geospatial Technology Manager
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>
