### ISSUE TITLE
MapProxy endpoint must use layer uuid in place of id

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#162]

**Comment by capooti** [comment]
In Registry this is already in place: https://github.com/cga-harvard/HHypermap/commit/f6a2e744a2b2d19aac0296dffd415aae4389f980

We have to modify the client accordingly.

**Comment by capooti** [comment]
Maybe here we can have Lennin working @ingenieroariel

**Comment by capooti** [comment]
@ingenieroariel I gave a test to this now and this is what I found after your code changes related to use the uuid in place of id:

* WM correctly works, style can be changed, edit raise an error but I believe this is because of the subdomain
* WMS layers work in preview, but they don't work when they are added to the map (this is a regression). Looking at the map configuration in db I still see the id in place of uuid, that could be the reason
* Warper layers work in preview, but they don't work when they are added to the map (this is a regression). Looking at the map configuration in db I still see the id in place of uuid, that could be the reason

I still need to test for ESRI layers

**Comment by ingenieroariel** [comment]
Thanks @capooti for the report.

Lennin will give help us with a fix tomorrow morning.
