### ISSUE TITLE
Updating the dataset for a layer clears all metadata for the layer

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#163]
"If you remove the old dataset and upload a new layer with the same name, then the link will be still the same, but you will loose all of the metadata and permissions and styles. You would need to re-create them."

**Comment by capooti** [comment]
This is expected. The problem here is that the user cannot upload a new version of the dataset for an existing layer because the corresponding code does not take into account that the layer could be in a different monthly database shard.
