### ISSUE TITLE
Use uuid as unique field in Solr schema

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#165]
We need to switch from id to uuid as the unique field in Solr to warrantee an unique index for each layer.
This may require a full reindex.

**Comment by capooti** [comment]
This is in production now, but the automation script is not finished.
The problem is that there is not a way using the Solr API to set uuid as unique.
@bglewis you can move this to a later milestone (or not milestone). @dsmiley will let us know when such a thing will be possible

**Comment by blewis** [comment]
I was talking to @dsmiley recently in contect of BOP and I thought he said solr was good at de-duplicating -- the context was tweed IDs

**Comment by capooti** [comment]
Maybe I was not clear. Our schema uses uuid as it should for the unique key, so we are ready for production.
What I could not accomplish is to automatize this in the code that generates the Solr schema from scratch: https://github.com/cga-harvard/HHypermap/blob/master/hypermap/aggregator/solr.py#L99
