### ISSUE TITLE
(after move to prod) base layer for hypersearch client has changed to google satellite for existing maps

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#170]
The base layer for hypersearch client has changed to google satellite for existing maps.  if one creates a new map the base layer is the original (and correct) google physical.

**Comment by capooti** [comment]
Hi @bglewis 
not sure if I understand:
1) new maps correctly have google physical
2) existing maps have always google satellite as a base layer?

Not sure why this could happened. Just checking with you if I understand correctly the problem.

**Comment by blewis** [comment]
This is not referring to the basemaps of the maps but to the basemap in the hypersearch search client accessed from within the maps.

Ben Lewis
Geospatial Technology Manager
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
Ok thanks for the clarification.
Though the base layer for both an existing map and a new map seem the same to me.

This is how it looks in an existing map:

<img width="1124" alt="screenshot 2016-12-02 15 07 26" src="https://cloud.githubusercontent.com/assets/148380/20836805/5b11381e-b8a1-11e6-94aa-fd3ccefc6759.png">

And this is how it looks for a new map:

<img width="1185" alt="screenshot 2016-12-02 15 07 51" src="https://cloud.githubusercontent.com/assets/148380/20836812/6470bad8-b8a1-11e6-8a95-786b181e49cc.png">
