### ISSUE TITLE
(after move to prod) layer pages not displaying from right click on layer on map "Share Layer"

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#171]

**Comment by capooti** [comment]
@ingenieroariel are you guys looking at this? I remember Lennin was taking care of it

**Comment by ingenieroariel** [comment]
Yes, we are looking into it.

**Comment by capooti** [comment]
Thanks @ingenieroariel

**Comment by ingenieroariel** [comment]
Is this other ticket a duplicate of this one @capooti https://github.com/cga-harvard/cga-worldmap/issues/173 ?

**Comment by ingenieroariel** [comment]
This works for new maps, is the problem happenning for old maps?

**Comment by capooti** [comment]
You are right, is working for new maps, did not realize that. If you open any old map the link seem broken. Maybe it is not even a Javascript thing then?

**Comment by ingenieroariel** [comment]
Lennin, can you help us spot differences in the two configurations as the come out from the server?

**Comment by ingenieroariel** [comment]
This has been fixed and deployed. Lennin will create a new PR for legacy before it can be formally closed.
