### ISSUE TITLE
Some WM layer in existing maps have a broken legend

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#174]
Like in this map (http://worldmap.harvard.edu/maps/2937) the layers Water Quality, Waste Water, Water Usage:

<img width="804" alt="screenshot 2016-12-02 17 04 25" src="https://cloud.githubusercontent.com/assets/148380/20840722/7c1ac74a-b8b1-11e6-8a4b-5f0beb44cfe0.png">

Also, editing the style for this layer is not working:

<img width="791" alt="screenshot 2016-12-02 17 04 52" src="https://cloud.githubusercontent.com/assets/148380/20840720/78de7c52-b8b1-11e6-9a86-148549eab316.png">

**Comment by ingenieroariel** [comment]
The style problem was one you told me was due to the use of http vs https right?

**Comment by capooti** [comment]
it looks like that but here is a different thing. I believe is some config missing in db, but had no time to check still

**Comment by capooti** [comment]
Fixed. It was connected to #183
