### ISSUE TITLE
Link representation on other sites

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#209]
Change from AfricaMap to WorldMap should be easy.

Comment from Prof.  

When one posts a link to a particular project, as I just did on Facebook for “The Progress of Love” the cover image is the old front image for Africa Map. It should show instead the cover image of whatever map someone has just done. If not that, then a generic WM icon or image.

**Comment by capooti** [comment]
Could you provide more details? thanks

**Comment by capooti** [comment]
@bglewis can you provide more info here? Thanks

**Comment by blewis** [comment]
Currently when a user adds a link pointing to a worldmap map or embed to facebook, an old image from AfricaMap shows up.

Ben Lewis
Geospatial Technology Manager
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
You mean this one?

<img width="505" alt="screenshot 2017-03-21 13 40 03" src="https://cloud.githubusercontent.com/assets/148380/24161859/f7b63e90-0e3b-11e7-9077-07805af0f22b.png">

**Comment by capooti** [comment]
Apparently facebook is using the last <img> from the html source code.
According to this [1] it should be possible to change the image. Do we have one to use in place of this one? If yes I can try to change it, it should take a few minutes.

[1] https://www.facebook.com/help/community/question/?id=10200814000150949

**Comment by blewis** [comment]
Here's an image
![worldmap](https://cloud.githubusercontent.com/assets/812849/25399496/a3aaa5e6-29bd-11e7-85d6-bf7e56a374b6.png)

**Comment by blewis** [comment]
The image above would replace the image of the Africa map.

**Comment by capooti** [comment]
This is done @bglewis
