### ISSUE TITLE
Deleting a layer from WorldMap has the potential to leave cruft behind in Dataverse (and a bad user experience)

### ISSUE THREAD

**Issue by pdurbin** [cga-harvard/cga-worldmap#214]
https://github.com/IQSS/dataverse/issues/3480#issuecomment-289029560 has some screenshots I just took. It would be nice if WorldMap said something like "this layer is in use by a dataset with a published DOI" or something. This is what the sees in WorldMap when deleting a map that has an association with a dataset in Dataverse:

![screen shot 2017-03-24 at 9 49 54 am](https://cloud.githubusercontent.com/assets/21006/24297851/89cf5c22-107a-11e7-8349-35272c224132.png)

**Comment by raprasad** [comment]
fyi: Due to the WorldMap upgrade process/schedule, this likely won't be added until 2018.  e.g. Any functionality added now has to be re-written post WorldMap migraton to the new geonode

**Comment by pdurbin** [comment]
We merged https://github.com/IQSS/dataverse/pull/3721 to fix the bad user experience on the Dataverse side described at https://github.com/IQSS/dataverse/issues/3480. I still think it would be nice if WorldMap users got a warning that the map they're deleting has an association with a published dataset but please feel free to close this if you disagree.

**Comment by capooti** [comment]
@pdurbin removing a map does not remove the layers contained in it.
With respect of removing a layer associated with a published dataset in Dataverse I am open: @bglewis what is your opinion about it?

**Comment by blewis** [comment]
Wouldn't this only hold for user = Dataverse which should know better?  That isn't to say it would be useless but would argue for doing it later when we only need to implement once.

**Comment by pdurbin** [comment]
Later is fine. Or not at all. 😄 

Sorry if I'm confusing "map" vs "layer" again. I think in the screenshot above it was a "layer" that I was deleting.

As far as I understand, Dataverse users are not creating their own WorldMap accounts. Rather, shared credentials are stored in Geoconnect and all layers are created by that WorldMap account (username "dataverse_user" according to https://github.com/IQSS/dataverse/issues/3495#issuecomment-291612958 ). End users shouldn't have the password so it should be rare that a layer is deleted directly from the WorldMap interface, which is what this issue is about. Again, please feel free to close this if it's hard to warn the user or if it's not worth doing because it's such an edge case.

**Comment by capooti** [comment]
OK, I am closing it, we can re-open if there is the need.
