### ISSUE TITLE
Layer added from Solr do not stay turned off after map is saved

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#216]
High priority.
The problem was discovered in this map but it happens for all maps.
https://worldmap.harvard.edu/maps/12239

**Comment by capooti** [comment]
I will fix this today.

**Comment by capooti** [comment]
This was fixed by this commit in GXP:
https://github.com/cga-harvard/gxp/commit/cfb9677f988163a8cb8c7df9655ae9d7f0effd68
