### ISSUE TITLE
Search by Location and Search by keyword do not work together

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/cga-worldmap#217]
This is with respect to http://worldmap.harvard.edu/maps/CHAwellness:
1. Search for Location e.g. Cambridge, MA
2. Search for "Hubway" in keyword search
3. No yellow dot/ no search result
However:
1. Refresh Map
2. Search for "Hubway" in keyword search
3. Many yellow dots/ search results
It appears that Search by Location and Search by keyword do not work together. Please refer to screenshots attached.

![pic1](https://cloud.githubusercontent.com/assets/11283176/24715319/f47f4d8e-19f8-11e7-93ff-65eff465e0b2.png)
![pic2](https://cloud.githubusercontent.com/assets/11283176/24715347/07bb2bca-19f9-11e7-8c6e-b74ace6baf6f.png)

**Comment by capooti** [comment]
For me it is working

**Comment by dkakkar** [comment]
Does not work for me. I did Step 1 followed by Step 2 i.e. search by location and keyword together.  I can show you what I am doing.

**Comment by capooti** [comment]
I have fixed this. The problem was with having two text box (the search text box in the gazetteer tool and the search text box in the search bar) having the same javascript id. This was affecting also #218 and #222 which I am closing as well.
