### ISSUE TITLE
Enter to activate Search by Location

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/cga-worldmap#219]
This is with respect to http://worldmap.harvard.edu/maps/CHAwellness:
Could you make it so that when a person pushes “Enter” when they are typing in the “Search by Location”, it activates the Search button automatically?

**Comment by capooti** [comment]
it will take a while. Should be this on every map I guess?

**Comment by dkakkar** [comment]
Yes

**Comment by capooti** [comment]
This is the only bug left now. It will require me 2 hours because the GazetteerTool.js would need to be refactored.

**Comment by blewis** [comment]
we can drop that for now
