### ISSUE TITLE
Enter to activate Search by Keyword

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/cga-worldmap#220]
This is with respect to http://worldmap.harvard.edu/maps/CHAwellness:
Could you have “enter” trigger the search function for the keyword search at the bottom

**Comment by capooti** [comment]
It will take a while. Must be this done on every map?

**Comment by dkakkar** [comment]
Yes.

**Comment by dkakkar** [comment]
Yes

**Comment by blewis** [comment]
If this is hard, forget it

**Comment by capooti** [comment]
Fixed.
