### ISSUE TITLE
Relabelling Search by Location

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/cga-worldmap#221]
This is with respect to http://worldmap.harvard.edu/maps/CHAwellness:
-Relabelling the "Search by Location" to "Search for an address or location"

**Comment by capooti** [comment]
Done. Note that the rendered text is "Search For An Address Or Location" with all uppercase first letters as defined by the CSS. If that is a problem we would need to work on the CSS.

**Comment by blewis** [comment]
that is fine
