### ISSUE TITLE
Clear "Enter search" in search bar

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/cga-worldmap#222]
This is with respect to http://worldmap.harvard.edu/maps/CHAwellness:
When you click in the keyword search, could you please make the text “Enter search…” disappear. (We currently have to manually delete it before entering search terms).

**Comment by capooti** [comment]
This is an easy fix. @bglewis do we need to have this fixed for all maps or just for the map @dkakkar is mentioning?

**Comment by dkakkar** [comment]
All maps.

**Comment by capooti** [comment]
Ok, anyway only this one is affected. just checked

**Comment by blewis** [comment]
If easy fix in all.  Or can be just fixed in new maps.

**Comment by capooti** [comment]
After some more investigations: we don't experience this for any other map but only for the Wellness Map (which is a fork of the standard map composer done 4 years ago, so out of sync with many stuff implemented meanwhile in the composer).
It looks like the text stays there only if first the "Search for an address or location" tool is opened.
This will require some investigations: how urgent is it?

**Comment by blewis** [comment]
Not urgent.  We will drop this for now.
