### ISSUE TITLE
TweetMap message redirecting to BOP

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#224]
High priority
Tweetmap which used to be hosted on a GPU server is being replaced with the Billion Object Platform or BOP.
When people hit URL https://worldmap.harvard.edu/tweetmap/, they should now get a message which says:

TweetMap is being enhanced to support real-time tweets, better search, and download of content via a new, open source, big streaming data system, the Billion Object Platform or BOP.  Click [here](http://bop.worldmap.harvard.edu/bop/) to play with an early Alpha version of the platform.  

Click [here](http://www.gis.harvard.edu/publications/building-open-source-real-time-billion-object-spatio-temporal-search-plaform) for information on the BOP project.   
Any questions please contact worldmap@harvard.edu.

**Comment by capooti** [comment]
I will work on this today.

**Comment by capooti** [comment]
Done it. Please advise if you need any changes.

**Comment by blewis** [comment]
Thanks.  Two things:  1) The "here" does not link "Click here for information on the BOP project." 2) The BOP URL is incorrect.  There must be a slash on the end "http://bop.worldmap.harvard.edu/bop/".

**Comment by capooti** [comment]
Done.
