### ISSUE TITLE
WorldMap Help PDF is out of date with regard to production bug in Harvard Dataverse

### ISSUE THREAD

**Issue by pdurbin** [cga-harvard/cga-worldmap#227]
http://worldmap.harvard.edu/static/docs/WorldMap_Help_en.pdf says

> Currently in production Dataverse https://dataverse.harvard.eduthere is a bug which prevents the “Map Data” button from reappearing once a dataset has been mapped. Until that bug is fixed you can practice using the development server here https://beta.dataverse.org.

but I believe this was fixed in Dataverse 4.6.1 as https://github.com/IQSS/dataverse/issues/3585

I found the PDF linked from http://worldmap.harvard.edu

Here's how it looks:

<img width="801" alt="screen shot 2017-04-11 at 12 55 30 pm" src="https://cloud.githubusercontent.com/assets/21006/24920865/d54f697c-1eb6-11e7-9fca-7bc855934136.png">

As you may know, the Dataverse team is working away on tabular mapping so if you want to wait to update the PDF until that work is done, that's fine. Here's how we're tracking it: https://github.com/IQSS/dataverse/issues?q=is%3Aopen+is%3Aissue+milestone%3A%224.6.2+-+Tabular+Mapping%22+label%3A%22Component%3A+WorldMap+%26+GeoConnect%22

**Comment by pdurbin** [comment]
This morning I confirmed with @raprasad and @sekmiller that the bug in question was indeed fixed in Dataverse 4.6.1 and has been in production at https://dataverse.harvard.edu for a month or so. Again, no rush to update the docs but I wanted to let you know.

**Comment by blewis** [comment]
Thanks Phil.  Uploading a corrected help.

**Comment by dlmurphy** [comment]
Hi Ben,

Just wanted to let you know - we've updated our geoconnect guide this past week, and it now includes a link to the Worldmap documentation at: http://worldmap.harvard.edu/static/docs/WorldMap_Help_en.pdf

I noticed that the outdated note that Phil mentioned previously on page 41 of the WorldMap documentation is still there - it sounds like you're putting up a corrected version soon?

**Comment by bglewis** [comment]
Sorry, I thought this change had been made. It will be made Monday.
Cheers,
Ben

**Comment by dkakkar** [comment]
I think its done, we did it on Friday. Could you please let me know if its
not.
