### ISSUE TITLE
Separate page for editing metadata contacts, authors

### ISSUE THREAD

**Issue by mbertrand** [cga-harvard/cga-worldmap#23]
Or leave on main metadata page and use autocomplete_light instead of select dropdowns.

**Comment by capooti** [comment]
I believe we can close this.
@bglewis any reason why we should have separate pages for editing metadata contacts and authors?

This is how it looks in WM (separate page from metadata):

<img width="1007" alt="screenshot 2017-01-27 15 35 04" src="https://cloud.githubusercontent.com/assets/148380/22386689/44c34f12-e4a6-11e6-8db6-f2bfdbc08b2f.png">

This is how it looks in GeoNode right now (in the metadata page):

<img width="867" alt="screenshot 2017-01-27 15 36 31" src="https://cloud.githubusercontent.com/assets/148380/22386730/6d975fb4-e4a6-11e6-998b-7c58539bd284.png">

**Comment by blewis** [comment]
we can close
