### ISSUE TITLE
Migrate mobile map functionality

### ISSUE THREAD

**Issue by mbertrand** [cga-harvard/cga-worldmap#24]
Make sure mobile map view still works in GN2

**Comment by capooti** [comment]
@bglewis do we need to migrate this as well? (which right now it does not seem to work)

**Comment by blewis** [comment]
we don't need to migrate this.  does latest geonode have a mobile solution?

**Comment by capooti** [comment]
I am not sure about it, but maybe with the new react client yes /cc @simod @ingenieroariel @jj0hns0n
