### ISSUE TITLE
Migrate to use of Template project (rather than branch/fork)

### ISSUE THREAD

**Issue by jj0hns0n** [cga-harvard/cga-worldmap#37]
We should migrate to the use of a template project that installs master from a package. Anything that can go upstream should, all worldmap specific overrides/extensions should go in the template project. It should be easy to install new upstream packages as we work through the release process for 2.1.

**Comment by capooti** [comment]
I am using it now for the migrated version, here is the new repository:
https://github.com/cga-harvard/worldmap
