### ISSUE TITLE
Custom group permissions - use Groups app instead?

### ISSUE THREAD

**Issue by mbertrand** [cga-harvard/cga-worldmap#40]
Worldmap has custom group permissions ("Harvard Users") that show up on permissions forms: http://i.imgur.com/E3CVvPv.png

Signup form has been customized with a radio-button option: http://i.imgur.com/lG2YICn.png

Some settings such as group name are customizable from settings.py: https://github.com/mbertrand/cga-worldmap/blob/gn20upgrade-merge/geonode/settings.py#L738

If user selects "Yes", redirected to Harvard authentication system, which then redirects to a Worldmap URL that assigns them to this group via "is_org_member" field on Profile model: https://github.com/mbertrand/cga-worldmap/blob/gn20upgrade-merge/geonode/worldmap/register/views.py#L104

Custom permissions for this group are here: 
https://github.com/mbertrand/cga-worldmap/blob/gn20upgrade-merge/geonode/security/enumerations.py#L27

https://github.com/mbertrand/cga-worldmap/blob/gn20upgrade-merge/geonode/security/enumerations.py#L33

https://github.com/mbertrand/cga-worldmap/blob/gn20upgrade-merge/geonode/security/auth.py#L123

But should probably be replaced with new groups app?

**Comment by capooti** [comment]
We will handle this with the Group model in new GN.
