### ISSUE TITLE
Created long text layer in CAMP and loaded to Map but no create feature button

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#519]
This is the layer
http://128.31.22.46/layers/geonode:long_text_test1

**Comment by capooti** [comment]
Thanks. This looks to be a bug, I am looking into it.

**Comment by capooti** [comment]
It happens when the layer is not downloadable for everyone.
In such a case the editing tools look disabled even for layer owner and even if layer owner is added to users which are let to download.

**Comment by capooti** [comment]
@blewis it is a very specific use case, to replicate:
* the user of the layer is not the owner (which is uncommon)
* the "Who can download?" permission is unset for "Anyone" (uncommon for WorldMap, common for CAMP)

As this is very time consuming to debug - and we can provide a workaround to the users (for example change the layer ownership or enable for just the editing session the download permissions for anyone - I would suggest to keep track of it and leave it at the bottom of the list. GeoFence looks involved after debugging it for a while.

**Comment by blewis** [comment]
For now the procedure will be that the creator of a new layer in CAMP will need to turn off downloading while editing.
