### ISSUE TITLE
URL Export - new approach

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#527]
1) Change "Add Selection" button at top of  Layer (or Map) list page http://128.31.22.46/layers/?limit=20&offset=0
to "URL to CSV".
2) Add new button to left of "+" (Select) button at upper right corner of each Layer (or Map) record.
The new button added will use a list icon.  A mouseover of the new button will return a tool tip which says "Add URL ".

Any map or layer selected using the "Get URL" button, will, when the "URL to CSV" button is clicked, be added to the URL to CSV list.  

Hitting the back button and adding more maps or layers by selecting them will keep adding them to the list.  Once the user has the list they like, they can can create the CSV.  On the list page:
1) Change "Selected Resources" to "Selected URLs"
2) Change "Export Layers to CSV" to "Export Layer URLs CSV"
3) Change "Export Maps to CSV" to  "Export Map URLs CSV"

**Comment by capooti** [comment]
This is done.
