### ISSUE TITLE
Sorting Maps and Layer doesn't work in Firefox, in Chrome it works after a few tries

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#530]

**Comment by capooti** [comment]
done it.

**Comment by capooti** [comment]
I see you moved back to the in progress area @blewis: is not working for you?

**Comment by blewis** [comment]
Now it seems to be working in terms of it being possible to sort in other ways after the default of Most Popular.   One more thing - the default selected item should be highlighted from the start.  Now it says it is Most Recent even though default is Most Popular.

**Comment by capooti** [comment]
Now the default sort (by popularity) is correctly selected in the template.

**Comment by capooti** [comment]
now also the default icon is properly set.
