### ISSUE TITLE
Can't edit layer I created

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#531]
User lubin
Here is the layer http://128.31.22.46/layers/geonode:bentest_layer_2 
Here is the map http://128.31.22.46/maps/1692/view

**Comment by capooti** [comment]
We already discussed about this here:
https://github.com/cga-harvard/geonode/issues/524
Workaround is to enable "download permissions to anyone" for the editing session.

**Comment by capooti** [comment]
As a side note, I would recommend to give that permissions by default when creating a layer. It will avoid this problem. And if they want to have a layer which is not downloadable then they can uncheck that.

**Comment by blewis** [comment]
agreed

**Comment by capooti** [comment]
done.
