### ISSUE TITLE
Lubin user can edit a layer he doesn't have permission to edit

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#532]
In this map http://128.31.22.46/maps/1659
Is this layer http://128.31.22.46/layers/geonode:quang_songwen owned by Admin2.
Admin 2 allows download by anyone but no editing of anything.
Lubin can edit style, and edit features from the Map UI even though on the Layer page it does not make metadata editing accessible.

**Comment by capooti** [comment]
In my browser the map behaves correctly.

![screenshot 2018-11-09 14 40 22](https://user-images.githubusercontent.com/148380/48284441-6c833700-e42d-11e8-9bae-6d6581a59c69.png)
