### ISSUE TITLE
cannot add layers from solr search UI to the map

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#534]

**Comment by capooti** [comment]
Thanks for reporting this. It looks like it does not work in Chrome, while in Firefox works for me. It could be something which was impacted after I fixed the Layers List yesterday. Will give a look.

**Comment by blewis** [comment]
Not working for me in firefox either

**Comment by capooti** [comment]
Looks to happen only for new maps. Working with existing maps. Looking into it.

**Comment by capooti** [comment]
This is fixed.
While debugging this I have realized that identify for layers added from the Solr interface is not working. Which explain many things. I am creating an issue and working directly on it.
