### ISSUE TITLE
Geonames features are not returned by gazetteer

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#535]

**Comment by capooti** [comment]
Maybe GeoNames is failing at this time? It was working for me two days ago, I will look at it later today.

**Comment by capooti** [comment]
This is fixed (I forgot to add the geonames key in the configuration)

**Comment by blewis** [comment]
Google places, if easy?

**Comment by capooti** [comment]
Situation: GeoNames, Nominatim and WM layers are on by default.
Google will require a valid key, so it does not make sense for CAMP but we can definitely activate it for new WM.
