### ISSUE TITLE
Mobile view not working for Maps- CAMP staging

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#537]
Mobile view is working for other parts of the system but Maps.  On legacy user is prompted when he hits a map whether to view in mobile view or not.  Mobile view is similar to minimized viewer client used in Map page.

**Comment by capooti** [comment]
This is done now.
Maybe you could tell them that their home page is not mobile friendly

**Comment by blewis** [comment]
Yes CAMP needs to fix their home page.  Also need to have zoom to location work and Identify.

**Comment by capooti** [comment]
Regarding the location zoom: looking at the browser console I see the following error "A Geolocation request can only be fulfilled in a secure context"
Checking online it looks like we need to have the site hosted with SSL in order for this to work. Read first answer here: https://stackoverflow.com/questions/37835805/http-sites-does-not-detect-the-location-in-chrome-issue
