### ISSUE TITLE
Old map links are broken as the maps id changed. Use a field to store that information 

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#562]
For example, for AfricaMap

Legacy:  http://worldmap.harvard.edu/maps/121/
Staging:  http://128.31.22.103/maps/40665/

**Comment by capooti** [comment]
Yes. This must be accomplished and I wanted to create a ticket with it. I will rename the ticket and put it in deliverable 2.

**Comment by blewis** [comment]
ok

**Comment by capooti** [comment]
I sent a PR to GeoNode and this will be fixed like this:
if a Map has a user url (for example 'AfricaMap') than that one is the official link. If there isn't a user url, then the link is the old id.

**Comment by capooti** [comment]
this is fixed.
