### ISSUE TITLE
WM Staging - loading layers from GeoNode layer list to map doesn't work

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#566]
Loaded 3 layers to cart
![image](https://user-images.githubusercontent.com/812849/49959233-0762ab80-fedb-11e8-8993-bf589a2a21b2.png)

After clicking create map only GAUL layer is loaded to Map on left though all 3 layers are loaded to map.
![image](https://user-images.githubusercontent.com/812849/49959342-50b2fb00-fedb-11e8-8d84-042597aadb93.png)

**Comment by capooti** [comment]
Thanks for reporting, will look into it. Also CAMP is affected with this.

**Comment by capooti** [comment]
Fixed it.
