### ISSUE TITLE
WM Staging - Can't upload shape or geotiff or geojson

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#567]

**Comment by capooti** [comment]
Upload looks slower now but worked for me for a shapefile.
GeoTiff seems broken and I have reported the bug in GeoNode repo: https://github.com/GeoNode/geonode/issues/4121

**Comment by blewis** [comment]
Sorry meant to add geojson.  Just edited title to this ticket

**Comment by blewis** [comment]
Tried to upload zipped shape and got this message
![image](https://user-images.githubusercontent.com/812849/49968630-5c5eeb80-fef4-11e8-84d8-6c50e184d39c.png)
Will send shape and geojson which are not working.

**Comment by capooti** [comment]
Please attach the shapefile to this ticket, because it can be related to the dataset.

**Comment by blewis** [comment]
now was able to upload shape and geojson though it was slow.  slowness caused by script running?

**Comment by capooti** [comment]
I paused the script now and the slowness is still there. Looking at logs, it looks like GeoServer is parsing all of the layers in the database, which makes thing slow. Even if we are uploading the shapefile to a small shard.

**Comment by capooti** [comment]
geotiff upload works for me. kml results in an error. Strangely this is not happening in my dev machine, therefore it could be related to the server configuration. I have reported the error here, let's see:
https://github.com/GeoNode/geonode/issues/4155

**Comment by capooti** [comment]
this is not happening now.
