### ISSUE TITLE
WM staging - could not edit attributes or geometry

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#569]
For this layer http://128.31.22.103/layers/geonode:buddhist_sites_1820_21
logged in as owner

**Comment by capooti** [comment]
Can you try again? This morning I made some changes on the configuration. Now seems working properly for me: using the same layer I can successfully edit data and change styles using a user which is not owner and admin but has the right permissions

**Comment by capooti** [comment]
I tried again, and works for me logged in with your user. Closing it.
