### ISSUE TITLE
WM staging - all maps have same AfricaMap Thumbnail

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#573]
This happened after I created a map thumbnail for AfricaMap. 
http://128.31.22.103/maps/?limit=20&offset=0

**Comment by blewis** [comment]
Whenever a thumbnail is created it is assigned to all Maps.

**Comment by capooti** [comment]
This is happening only for migrated maps because in the migration script the uuid is incorrectly set to the same value for all maps. I will create a script to change uuid for maps which have same uuid.
It is not happening for freshly created maps as the UUID is correctly generated by GeoNode.

**Comment by capooti** [comment]
fixed it.
