### ISSUE TITLE
WM Staging - layers dissapear after saving map for first time

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#575]
After saving layers these local layers disappeared
http://128.31.22.103/maps/46604/view

**Comment by blewis** [comment]
Adding a another remote layer and the map saves.  This is the layer I added
http://128.31.22.134/registry/hypermap/layer/0a59d11f-2a47-4ecc-9f03-2b69cac0fcbc/
To create  http://128.31.22.103/maps/46605/view

**Comment by capooti** [comment]
The local layers are not showing up because for some reason in Solr we have as layer name: 'layer_name'. Instead it should be 'geonode:layer_name'.
I am not sure why this is different from the CAMP instance (where it is in the correct form). Will fix it tomorrow morning.

**Comment by capooti** [comment]
This was the same as #458
