### ISSUE TITLE
WM Staging - print button does not work

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#576]
Tried using this map with this remote layer http://128.31.22.103/maps/46605/view

**Comment by capooti** [comment]
Confirmed. Will fix it.

**Comment by capooti** [comment]
This looks to not work correctly for old maps. Let's wait every layer in GeoServer is fixed and then we can test it again.
For now if you look at most recent maps, and if you create thumbnails for them, it works correctly

**Comment by capooti** [comment]
We need to write this script: https://github.com/cga-harvard/geonode/issues/570
I can do it as a very first thing for the final deliverable.

**Comment by capooti** [comment]
fixed it.
