### ISSUE TITLE
WM Staging - when using text search for Maps, no results returned

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#580]
See below

![image](https://user-images.githubusercontent.com/812849/50181215-c81ccc00-02d9-11e9-8585-e8c3f282cccc.png)

**Comment by capooti** [comment]
I think it works as far as you don't click on the selected item. But agree, is a GeoNode bug, will fix this at some point

**Comment by blewis** [comment]
Low priority but it is strange behavior as there is a clear opportunity when a user selects that one thing to give them what they clicked on.

**Comment by capooti** [comment]
I sent a PR to fix this in GeoNode. Tomorrow will be merged.

**Comment by capooti** [comment]
fixed it.
