### ISSUE TITLE
WM Staging - when using text search for Layers, no results returned

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#581]
See below

![image](https://user-images.githubusercontent.com/812849/50181342-16ca6600-02da-11e9-925e-141c16528bdc.png)

**Comment by capooti** [comment]
can't these things postponed to the final deliverable?
If you hit enter and not use the mouse search is working

**Comment by blewis** [comment]
yes

**Comment by capooti** [comment]
I sent a PR to fix this in GeoNode. Tomorrow will be merged.

**Comment by capooti** [comment]
fixed it.
