### ISSUE TITLE
Some maps fails to save because contains layers with broken GeoServer XML REST response

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#582]
I opened this map which I own http://128.31.22.103/maps/40682/view and changed basemap from Google to OSM and tried to save. It gave this error.  

![image](https://user-images.githubusercontent.com/812849/50181543-af60e600-02da-11e9-8d07-cc809abee170.png)

Then when I looked at the Map, all the layers were gone, but the base layer had changed.

![image](https://user-images.githubusercontent.com/812849/50181659-ff3fad00-02da-11e9-84a2-1b2626e8afe7.png)

This is what the original Map in WorldMap looks like http://worldmap.harvard.edu/maps/global

**Comment by capooti** [comment]
check my previous comment, this is caused by problem with data in GeoServer

**Comment by capooti** [comment]
In this specific case this is the error which causes the issues:

```
Exception: ('GeoServer gave non-XML response for [GET http://128.31.22.83:8080/geoserver/rest/layers/geonode%3Aams.xml]: <layer>\n  <name>ams</name>\n  <type>RASTER</type>\n  <defaultStyle class="dynamic-proxy"Unable to marshal reference with no id or name.', ParseError(ExpatError('not well-formed (invalid token): line 4, column 37',),))
[pid: 6925|app: 0|req: 22/151] 127.0.0.1 () {52 vars in 1107 bytes} [Wed Dec 19 16:20:54 2018] PUT /maps/40682/data => generated 40891 bytes in 854 msecs (HTTP/1.0 500) 8 headers in 276 bytes (1 switches on core 0)
```

These kind of issues should be addressed by the script which fixes GeoServer REST XML response.

**Comment by capooti** [comment]
This is being caused by missing raster files in GeoServer data directory. I will fix the code in the following way: It will still save the map, but remove the invalid layer (in this case a missing file)

**Comment by capooti** [comment]
This is now fixed. I removed two layers which were not existing anymore in GeoNode.
