### ISSUE TITLE
WM staging - clould not edit style of layer I own

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#583]
http://128.31.22.103/layers/geonode:trump_international_ue2

**Comment by capooti** [comment]
this is generally caused by the expiration of the OAuth token when your browser session is inactive for a while. Could you try to logout, login again and re-try to edit the style?

**Comment by capooti** [comment]
Could you do what I suggested and see if it replicates? thanks

**Comment by capooti** [comment]
@bglewis check this discussion: https://github.com/GeoNode/geonode/issues/3563

I have now set ACCESS_TOKEN_EXPIRE_SECONDS to 1 year. If you again are unable to edit data or styles for any layer which you believe you have permissions let me know because in that case this didn't help.

**Comment by capooti** [comment]
Unfortunately changing this setting seem not having fixed things.

**Comment by capooti** [comment]
Closing this, we have another one open.
