### ISSUE TITLE
Map came up without base layer when set, gave error

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#594]
I opened this map http://128.31.22.103/maps/lukescobarethnic/view  and it had no base layer (maybe it was Bing but that was not displaying)
So I set to OSM and tried saving, got this message.
![image](https://user-images.githubusercontent.com/812849/55027028-a74fcb00-4fda-11e9-8f20-b80d49dc2c95.png)

**Comment by capooti** [comment]
this now opens correctly.
