### ISSUE TITLE
Zoom to layer extent doesn't work

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#595]
http://128.31.22.103/layers/geonode:buddhist_sites_1820
When layer is  loaded to a map.

**Comment by capooti** [comment]
I noticed that it is not working with some projections. For example in this case it works:
http://128.31.22.103/maps/new?layer=geonode:ch_HSR_st_2011

I will check why and let you know.

**Comment by capooti** [comment]
I just deployed a fix for this. Could you try it?
I changed part of the core map implementation, so it is likely that something different could be broken.
