### ISSUE TITLE
Identify does not work on worldmap staging 

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#597]
Identify does not work on Boston Research Map http://128.31.22.103/maps/boston/view .  On Firefox browser there is no response.  On Chrome and IE the page returns an error.  
![image](https://user-images.githubusercontent.com/812849/56310316-9433a500-6119-11e9-9df2-f12a7c2747af.png)

Opening another map ChinaXmap in Firefox identify brings up spinning wheel and never resolves.

**Comment by capooti** [comment]
Yes, something is weird with this map. I notice a number of javascript errors when loading the map details page. I will need to debug this - the other maps look working properly

![Screenshot 2019-05-10 17 19 54](https://user-images.githubusercontent.com/148380/57557387-f57d1b80-7347-11e9-89ea-e405e3299d73.png)

**Comment by capooti** [comment]
This is fixed.
