### ISSUE TITLE
Cannot edit style on WorldMap staging with a user which is not the layer owner

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#598]
We know of the problem for a layer owner to create new styles but we had been able to edit existing styles.  Now we cannot.  Is this related to geosolutions update?    http://128.31.22.103/layers/geonode:workshop_suitability .  Logged in as blewis, using Firefox on windows.

**Comment by capooti** [comment]
With my test user I can edit an existing style for this layer and create a new style when I have permissions.
I agree, though, that the widget should be faster, as now if the user doesn't wait until the response is complete the style won't change

**Comment by capooti** [comment]
@blewis could you please check if you are still experiencing this? For me it works

**Comment by blewis** [comment]
I could not edit style for http://128.31.22.103/layers/geonode:MajorRivers_World_selected_p3w
this was shared for style editing with bgreenelewis by blewis.   I could create a new style with bgreenelewis but not edit an existing style.  I could use the widget but the change did not take.  Even after waiting.

**Comment by capooti** [comment]
oh so it is a different issue. Let me rename it and will check it.

**Comment by capooti** [comment]
This works correctly on CAMP and WM staging now.
