### ISSUE TITLE
Created a map on worldmap staging and cannot view it 

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#599]
http://128.31.22.103/maps/46673 
The map version is viewable but does not have public persmission it seem because the map returns an error if a non-logged in person tries to view it.
http://128.31.22.103/maps/46673/view
Because it is impossible to get to the map details page it is impossible to see what the permissions are set to.

**Comment by capooti** [comment]
confirmed. It seems there is an issue accessing map details page by id, while it works correctly if accessing it by name. I see the problem only for this specific map, and not for others.

**Comment by capooti** [comment]
This is now fixed.
