### ISSUE TITLE
Measure tool

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#60]
Need an easy way to let users draw a line or polygon and measure approximate distance or area in miles/sq miles or kilometers/sq kilometers.

**Comment by robertlight** [comment]
Ben,

You could easily use the code I wrote for the Edx/XBlock connector to create a simple measuring tool - the xy locations can easily be converted to lonlat and from there it's an easy calculation to get distance.   The polygon tool can give you an area which (at least for relatively small areas) you can use the JTS tools to calculate an area and convert to sqkm or sq-mi.

**Comment by blewis** [comment]
Thanks Bob.

Ben Lewis
Center for Geographic Analysis, Harvard
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
This was done some weeks ago.
