### ISSUE TITLE
WorldMap Staging can't create a layer

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#601]
Tried to create a layer and getting an error 
"'NoneType' object has no attribute 'connection_parameters' (<type 'exceptions.AttributeError'>)"

![image](https://user-images.githubusercontent.com/812849/57483274-7539b600-7274-11e9-9dd7-40267b009bd0.png)

**Comment by capooti** [comment]
This just worked for me. Can you try again?
