### ISSUE TITLE
CAMP staging - registering doesn't send validation email

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#602]

**Comment by capooti** [comment]
I tried to register as a new user, but I see that now GeoNode wants to have an administrator to validate it. I think some settings changed with latest code: I guess we should  get back to the way we were used? (no need for validate a user after registration), am I correct?

**Comment by blewis** [comment]
If that is how CAMP production is set up

**Comment by capooti** [comment]
this is a bug in GeoNode, for now I filed a new issue here:
https://github.com/GeoNode/geonode/issues/4413

**Comment by capooti** [comment]
I will check if this is already fixed in GeoNode once I sync with latest code (during next week, in the code sprint)
