### ISSUE TITLE
Problem with regular user having admin permissions on CAMP staging

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#608]

**Comment by capooti** [comment]
This seems to me a GeoNode regression. I will check GeoNode master and see if the problem is there as well.

**Comment by capooti** [comment]
Now it is good.

**Comment by blewis** [comment]
I'm logged in as Lubin and can change style for this layer http://128.31.22.46/layers/geonode:cbdb_female_1

**Comment by capooti** [comment]
I got this same problem now. I changed the permissions again and then it is working - ie lubin can't edit the style. It looks like some action using the permissions widget will explode the vulnerability. I will make some extensive tests on this. This is NOT connected to GeoServer/GeoFence but only to Django

**Comment by capooti** [comment]
I am closing this. If you experience something like this again we can re-open it, but can't reproduce it once I set the permissions again on the layer.
