### ISSUE TITLE
Can edit style for layer I don't have permission to edit

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#612]
I can edit style for this layer http://128.31.22.46/layers/geonode:harvard_yenching_scholars_number
in this map http://128.31.22.46/maps/1818/view 
which I don't have permission to edit, as user lubin.

![image](https://user-images.githubusercontent.com/812849/57795765-c9311880-7714-11e9-8058-cb3fe0971a44.png)

**Comment by capooti** [comment]
thanks @bglewis I replicated the issue. Will look into this

**Comment by capooti** [comment]
Right now when logged as "lubin" I cannot edit the styles. Not sure why this was happening.

**Comment by capooti** [comment]
Now we are using very latest GeoNode code, so it could have been a regression which is now fixed.
