### ISSUE TITLE
CAMP staging tried to load this layer to an existing map from the map page

### ISSUE THREAD

**Issue by blewis** [cga-harvard/cga-worldmap#616]
On this layer page  http://128.31.22.46/layers/geonode:xiandaizuojiamidu_1    I tried to load this layer to map Bentest3 and got error 
![image](https://user-images.githubusercontent.com/812849/58718021-8f117900-839a-11e9-947e-4accb89bd510.png)

, then tried to load to Bentest10 and it hung and did not complete

**Comment by capooti** [comment]
This looks working randomly.

**Comment by capooti** [comment]
I can't replicate it right now.
