### ISSUE TITLE
Fix layer edit and create

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/cga-worldmap#78]

**Comment by capooti** [comment]
worked fo me a while back ago

**Comment by ingenieroariel** [comment]
Could be caused by not having #77 in place.

**Comment by capooti** [comment]
Yes. I think - but could be wrong - that @mbertrand used a watchdog to detect it GeoNode authentication plugin was broken and in such a case GeoServer was restarted.
We had this problem in the WFP instance as well, and we were monitoring a private layer with a watchdog that was sending a WMS GetFeatureInfo request. In case the XML response was giving error GeoServer was restarted.
Please note that this problem has been addressed by GeoSolutions, and now current authentication plugin in GeoServer that comes with GeoNode (2.7) should not be affected anymore.

**Comment by mbertrand** [comment]
Yes, the script used curl to download a map tile for a layer that was restricted to a certain user.  If the size of the downloaded image was < x KB (indicating a blank tile) then geoserver  would be restarted.

I think the location of these scripts on the server is ~/root/scripts

**Comment by ingenieroariel** [comment]
This is now enabled as a cronjob called checktile.sh that is running every 15 minutes. When this condition is detected, the main tomcat is restarted while the second tomcat (tomcatb) serves all the requests.

**Comment by capooti** [comment]
thanks @ingenieroariel, this is great
what would happen if authentication is broken in tomcatb?

**Comment by ingenieroariel** [comment]
Tomcatb is not being checked for authentication but it is being checked at
the logs level. If tomcatb goes kaboom it should be restarted gracefully
too.
