### ISSUE TITLE
Re-enable daily backup scripts

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/cga-worldmap#82]

**Comment by capooti** [comment]
GeoServer backup I assume, as RDS backup can be scheduled from AWS console?

**Comment by ingenieroariel** [comment]
RDS is all backed up automatically, I am talking about hard drives for wm-django and wm-java

**Comment by ingenieroariel** [comment]
We need to backup:

a) GeoServer data dir, this can be done with EBS snapshots of that drive
b) Java VM instance backup
c) Django VM instance backup

Where should we do this from? this does not happen at the machine level but at the AWS level, it is better if it is running on a server outside of the production infrastructure.

**Comment by capooti** [comment]
@bglewis what about a small instance to handle this kind of stuff?

**Comment by ingenieroariel** [comment]
I think it is a good idea to put a micro instance to handle this stuff. We can configure the ansible scripts for provisioning that I have on my computer too.
