### ISSUE TITLE
Permissions on worldmap.log file are changed when logs are located

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#85]
For now we have a crontab that every minutes sets again the correct permission for the file /home/ubuntu/legacy/worldmap.log
But in the long run we need to avoid that rotation changes the permission.

**Comment by ingenieroariel** [comment]
Closing.

**Comment by capooti** [comment]
thanks ariel!

On Mon, Dec 28, 2015 at 5:54 PM, Ariel Núñez <notifications@github.com>
wrote:

> Closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cga-harvard/cga-worldmap/issues/85#issuecomment-167602713>
> .
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
