### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#90]
Going to this map: http://worldmap.harvard.edu/maps/7706 

we get:

Internal Server Error: /maps/7706Traceback (most recent call last):

  File "/home/ubuntu/venvs/legacy/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "./geonode/maps/views.py", line 786, in view
    config = map_obj.viewer_json(request.user)

  File "./geonode/maps/models.py", line 1858, in viewer_json
    config["map"]["layers"][len(layers)-1]["selected"] = True

IndexError: list index out of range

**Comment by mbertrand** [comment]
The map has no layers at all, not even baselayers:

http://worldmap.harvard.edu/admin/maps/map/7706/

**Comment by capooti** [comment]
It would be interesting to debug what caused to have an empty map in the system.

**Comment by mbertrand** [comment]
It's possible to manually remove every layer on a map, though I don't know why anyone would want to.
