### ISSUE TITLE
Create a scripts to delete duplicated caches

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/cga-worldmap#95]
The script should:
- [ ]  grep the geoserver log frequently (running as a cronjob or via monit.
- [ ] identify when the exception below is present
- [ ] extract the layer name from it
- [ ] grep the gwc-layers directory for the layer name and delete any LayerImpl file that contains it
- [ ] stop tomcata and tomcatb

This will make the site unavailable for around 10 minutes while the server is restarted. Such a problem does not exist in the latest versions of GeoServer/GeoNode as bad layers like that do not cause a full site failure.

```geoserver.log.1:Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gwcTLDispatcher' defined in URL [jar:file:/mnt/sdp/opt/tomcat/b/webapps/geoserver/WEB-INF/lib/gwc-2.3-SNAPSHOT.jar!/geowebcache-core-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.geowebcache.layer.TileLayerDispatcher]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: value already present: geonode:crossing_points_696
geoserver.log.1:Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.geowebcache.layer.TileLayerDispatcher]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: value already present: geonode:crossing_points_696
geoserver.log.1:Caused by: java.lang.IllegalArgumentException: value already present: geonode:crossing_points_696

```
```

**Comment by capooti** [comment]
I think it should be enough to remove stuff from the cache (grep the gwc-layers directory for the layer name and delete any LayerImpl file that contains it) no need to delete from wmdata.
Next time we experience this we can check.

**Comment by ingenieroariel** [comment]
```grep "Caused by: java.lang.IllegalArgumentException: value already present" ../logs/geoserver.log
```

**Comment by capooti** [comment]
I have worked on the script today, and put it in production. Let's see how it works.

**Comment by capooti** [comment]
done it.
