### ISSUE TITLE
ECW plugin is not working properly

### ISSUE THREAD

**Issue by capooti** [cga-harvard/cga-worldmap#97]
Now that we have the ECW plugin installed, unluckily I cannot make it working.
If I create an ecw store using one of these images: http://www.terracolor.net/sample_imagery.html
I can succesfully create the ecw store in GeoServer, publish the layer and run updatelayers on GeoNode.
But when accessing the layer page, like here: http://worldmap.harvard.edu/data/geonode:Terracolor_SanFrancisco_US_15m

I get the error: "Error rendering coverage on the fast path. java.lang.IllegalArgumentException: Band number 3 is not valid"

On the server ecw gdal support works correctly. I have tested it by running gdal_translate on a ecw image to a tiff output, and the image is correctly exported.
Unluckily I am not sure what to do know. I spent almost 2 days on this and no results. And having an obsolete GeoServer version on the server cannot help if we ask help on the GeoServer list.

@bglewis would it be a viable solution to export the data to tiff?

**Comment by blewis** [comment]
Sorry about that!  I think Matt Bertrand can help.  Set a time to talk to him?
Ben

Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by capooti** [comment]
I believe the problem is with the default SLD associated with new raster. Let me try a couple of things, maybe I can fix it.

**Comment by capooti** [comment]
Yes my suspect was correct.
Now it works:
http://worldmap.harvard.edu/data/geonode:Terracolor_SanFrancisco_US_15m

For some reason there is a GS raster default style that is not suitable to 3 bands raster like for ecw. Workaround is to manually associate the "GenericGeoTIFF" style to the layer in place of the default one, named "raster".
Or we can change the default raster to it, but not sure if this could have other consequences.

**Comment by capooti** [comment]
done it.
